"""
Stage 13 — assemble docs/VALIDATION_SUMMARY.md from results/, not from memory.

Every table in the summary is read out of a CSV that a numbered script wrote, so
the document cannot drift away from the run that produced it. Regenerate it
after any rerun.
"""
from _common import ROOT, Stage, written

import pandas as pd

from moduleb import config, dataio
from moduleb.constants import PARAMS

DOC = ROOT / "docs" / "VALIDATION_SUMMARY.md"


def md_table(df: pd.DataFrame, floats: int = 5) -> str:
    d = df.copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].map(lambda x: f"{x:,.{floats}f}" if pd.notna(x) else "")
    head = "| " + " | ".join(str(c) for c in d.columns) + " |"
    rule = "|" + "|".join("---" for _ in d.columns) + "|"
    body = "\n".join("| " + " | ".join(str(v) for v in row) + " |"
                     for row in d.itertuples(index=False))
    return "\n".join([head, rule, body])


def read(name: str) -> pd.DataFrame:
    p = dataio.RESULTS / name
    if not p.exists():
        raise SystemExit(f"{name} is missing — run the stage that writes it first")
    return pd.read_csv(p)


def main() -> int:
    with Stage("STAGE 13 — build the validation summary"):
        cvm = read("03_cv_metrics.csv")
        pt = read("03_paired_lot_test.csv")
        pv = read("03_per_variant.csv")
        nf = read("03_noise_floor.csv")
        bf = read("04_best_vs_frozen.csv")
        calm = read("05_calibration_metrics.csv")
        calc = read("05_calibration_vs_cv.csv")
        calp = read("05_calibration_paired_test.csv")
        ft = read("06_predeclared_falltime_decision.csv")
        cov = read("09_envelope_coverage.csv")
        rates = read("08_reason_code_rates.csv")
        hashes = read("00_input_hashes.csv")

        ft_long = ft.T.reset_index()
        ft_long.columns = ["field", "value"]

        meta = dataio.load_dataset_version()
        digest = config.frozen_config_digest()

        cv_tab = (cvm[cvm.variant == "ALL"]
                  .pivot(index="param", columns="model", values="MAE")
                  .loc[PARAMS, ["Persistence", "LinExtrap", "MedianRatio_24h", "MODULE_B"]]
                  .reset_index())

        bias = (cvm[(cvm.variant == "ALL") & (cvm.model == "MODULE_B")]
                [["param", "MAE", "MedAE", "P90AE", "RMSE", "MeanSignedError",
                  "UnderPredRate", "MacroLotMAE", "WorstLotMAE", "nMAE_pct"]])

        cal_tab = (calm[(calm.variant == "ALL")]
                   .pivot(index="param", columns="model", values="MAE")
                   .loc[PARAMS].reset_index())

        op = cov[cov.tau == config.ENVELOPE_TAU][
            ["param", "marginal_coverage", "tail_coverage", "mean_rel_width"]]

        rc = (rates[(rates.split == "calibration") & (rates.param == "ANY")]
              [["code", "n_fired", "rate"]].sort_values("rate", ascending=False))

        txt = f"""# Module B validation summary

**Dataset** `{meta['dataset_id']}` · split `{meta['split_id']}` · generator
`{meta['generator_version_public']}` · {meta['rows']} rows, {meta['lots']} lots
**Config digest** `{digest}`
**Generated by** `scripts/13_build_validation_summary.py` from `results/`. Every
table below is read out of a CSV a numbered script wrote; none of it is typed by
hand.

## 1. Inputs, by hash

{md_table(hashes[['file', 'bytes', 'sha256']], 0)}

## 2. Validation protocol

- Whole-lot `GroupKFold`, {config.N_FOLDS} folds, lots dealt round-robin within
  each variant. Deterministic from the lot names.
- Significance on **per-lot** MAEs, two-sided Wilcoxon signed-rank. 42 lots is
  the sample size, not 3,151 rows.
- Differences under **{config.TIE_THRESHOLD_PCT:.0f}% MAE are ties**, whatever
  the rank or the p-value.
- Seed `{config.GLOBAL_SEED}`. No randomness outside the seeded conformal draw.

## 3. Whole-lot CV on the 42 training lots — MAE

{md_table(cv_tab)}

## 4. Module B vs median-ratio — the number to quote

{md_table(pt[['param', 'MacroLotMAE_module_b', 'MacroLotMAE_median_ratio', 'gain_pct',
              'n_lots', 'lots_won', 'wilcoxon_p', 'verdict']])}

The MAE columns here are **macro-lot** means (every lot weighted equally); the
table in section 3 is the row-weighted pooled MAE. The two differ slightly
because the lots are not the same size.

## 5. Per-variant MAE and gain — is one variant carrying the result?

{md_table(pv, 4)}

## 6. Stability and bias

`MeanSignedError < 0` means systematically low, which is the dangerous direction
for screening. `WorstLotMAE / MacroLotMAE` is the spread across held-out lots.

{md_table(bias)}

## 7. Distance from the assumed measurement-noise floor

{md_table(nf)}

## 8. The 24-configuration grid — nothing beats the frozen config

Threshold for a real difference: {config.TIE_THRESHOLD_PCT:.0f}%.

{md_table(bf)}

## 9. Held-out calibration lots (12 lots, model fitted on all 42 train lots)

{md_table(cal_tab)}

### Calibration vs internal CV

{md_table(calc)}

### Paired per-lot test on the calibration lots

Twelve lots, so much less power than the 42-lot CV. A non-significant p here
means "not enough lots to tell", not a contradiction of section 4.

{md_table(calp[['param', 'macro_lot_mae_a', 'macro_lot_mae_b', 'gain_pct',
                'lots_won', 'n_lots', 'wilcoxon_p', 'verdict']])}

## 10. The pre-declared Output_Fall_Time decision

{md_table(ft_long, 4)}

## 11. Prediction envelope at tau = {config.ENVELOPE_TAU}

Marginal coverage is calibrated. **Tail coverage is not**, and the envelope is
therefore evidence for fusion rather than a screen.

{md_table(op, 4)}

## 12. Reason-code firing rates (calibration)

Acceptance: no single code above {config.MAX_FLAG_FIRING_RATE:.0%}, no more than
{config.MAX_ANY_FLAG_RATE:.0%} of components carrying any code.

{md_table(rc, 4)}

## 13. Known limitations carried into the freeze

No technical decision about current-release behaviour is open. Everything below is a
measured limitation that travels with the release rather than a question still to be
answered; future work is parked in `docs/FUTURE_RELEASE_ITEMS.md`.

- `FORECAST_REL_DELTA_CAP` is `{config.FORECAST_REL_DELTA_CAP!r}`. **D11 closed 19 Sep
  with the cap OFF** — every candidate value was post-hoc on calibration, the motivating
  case is a true positive with an exaggerated magnitude, and no independently justified
  bound is also effective. The freeze preflight fails if the cap is not `None`.
  *(This section previously read "this must be decided before the freeze"; that was
  stale from the moment D11 closed — corrected 19 Sep, round 2.)*
- `Input_Leakage_Current` is worse than median-ratio on the calibration lots,
  driven by one component of 906. Reported as a failure in
  `docs/ACCEPTANCE_CRITERIA.md` (M5), not reframed.
- The timing forecasts and every evidence column are **cohort** statistics; a lot must
  be proved complete before it is served (D12, D15).
- The p95 envelope is **evidence, never a screen**: marginal coverage is calibrated,
  tail coverage is 0.407-0.769 and is reported as measured.
"""
        DOC.write_text(txt)
        written(DOC)
        print(f"  {len(txt.splitlines())} lines, {len(txt)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
